theme: jekyll-theme-minimal
title: Pineloch Sun Beach Club
logo: /assets/images/pls_logo.jpg
sidebar_pages:
   lorens_latest: Loren's Latest
   cameras: Lodge Cameras
   documents: Documents
   board_of_directors: Board of Directors
   tips_and_tricks: Tips and Tricks
