remote_theme: daviddarnes/alembic@main
plugins:
- jekyll-remote-theme
title: Pineloch Sun Beach Club
logo: /assets/images/pls_logo.jpg
sidebar_pages:
   lorens_latest: Loren's Latest
   cameras: Lodge Cameras
   upcoming_events: Upcoming Events
   documents: Documents
   board_of_directors: Board of Directors
   tips_and_tricks: Tips and Tricks
   local_resources: Local Resources
